server:
  port: 9000
dubbo:
  application:
    id: fx_consumer
    name: fx_consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  monitor:
    protocol: registry
  metadata-report:
    address: zookeeper://127.0.0.1:2181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hmily_fx1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234

